import openai
from fastapi import HTTPException
import os

# Fetch OpenAI API key from environment variable
""" openai.api_key = os.getenv("OPENAI_API_KEY")
if not openai.api_key:
    raise HTTPException(status_code=500, detail="OpenAI API key not found") """

# Test if the key is loaded
print(f"Loaded OpenAI API Key: {openai.api_key}")

# Function to call OpenAI API
def call_openai_api(prompt: str):
    print("Received prompt:")
    print(prompt)
    try:
         # Placeholder response (simulating OpenAI response)
        response_placeholder = {
            "choices": [
                {"text": "This is a placeholder comparison generated by OpenAI."}
            ]
        }

        # Print the placeholder response
        print("OpenAI Response:")
        print(response_placeholder["choices"][0]["text"])

        return response_placeholder
        
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Error calling OpenAI API: {str(e)}")
