version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0" 
    ports:
      - 8000:8000
    # use this if wanting to sync all changes to docker container
    volumes:
      - .:/app